IF EXISTS(SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE SPECIFIC_NAME = 'GetUserById')
DROP PROCEDURE [dbo].[GetUserById]
GO
CREATE PROCEDURE [dbo].[GetUserById]
    @userId UNIQUEIDENTIFIER
AS
BEGIN
SETNOCOUNTON;
    SELECT *
    FROM Users
    WHERE userId = @userId
END
GO
    